//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Don_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chi_Tiet_Don_Hang()
        {
            this.Danh_Gia = new HashSet<Danh_Gia>();
        }
    
        public int ID_DON_HANG { get; set; }
        public string MA_SP { get; set; }
        public int SO_LUONG { get; set; }
        public decimal GIA_BAN { get; set; }
    
        public virtual Don_Hang Don_Hang { get; set; }
        public virtual San_Pham San_Pham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danh_Gia> Danh_Gia { get; set; }
    }
}
