//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Web_Entities : DbContext
    {
        public Web_Entities()
            : base("name=Web_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual DbSet<Danh_Gia> Danh_Gia { get; set; }
        public virtual DbSet<Danh_Muc> Danh_Muc { get; set; }
        public virtual DbSet<Don_Hang> Don_Hang { get; set; }
        public virtual DbSet<Gio_Hang> Gio_Hang { get; set; }
        public virtual DbSet<Khach_Hang> Khach_Hang { get; set; }
        public virtual DbSet<Lich_Su_Don_Hang> Lich_Su_Don_Hang { get; set; }
        public virtual DbSet<Nha_Xuat_Ban> Nha_Xuat_Ban { get; set; }
        public virtual DbSet<Phuong_Thuc_Thanh_Toan> Phuong_Thuc_Thanh_Toan { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<San_Pham> San_Pham { get; set; }
        public virtual DbSet<Tac_Gia> Tac_Gia { get; set; }
        public virtual DbSet<The_Loai> The_Loai { get; set; }
        public virtual DbSet<Trang_Thai> Trang_Thai { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
