//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gio_Hang
    {
        public string MA_KH { get; set; }
        public string MA_SP { get; set; }
        public int SO_LUONG { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
    
        public virtual Khach_Hang Khach_Hang { get; set; }
        public virtual San_Pham San_Pham { get; set; }
    }
}
