//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lich_Su_Don_Hang
    {
        public int ID { get; set; }
        public int ID_DON_HANG { get; set; }
        public int ID_TRANG_THAI { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual Don_Hang Don_Hang { get; set; }
    }
}
