//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phuong_Thuc_Thanh_Toan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phuong_Thuc_Thanh_Toan()
        {
            this.Don_Hang = new HashSet<Don_Hang>();
        }
    
        public int ID_THANH_TOAN { get; set; }
        public string TEN_PHUONG_THUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Hang> Don_Hang { get; set; }
    }
}
