//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(San_PhamMetadata))]

    public partial class San_Pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_Pham()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
            this.Gio_Hang = new HashSet<Gio_Hang>();
        }
    
        public string MA_SP { get; set; }
        public string TEN_SP { get; set; }
        public string MO_TA { get; set; }
        public string HINH_ANH { get; set; }
        public decimal GIA_GOC { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<decimal> GIA_BAN { get; set; }
        public int TON_KHO { get; set; }
        public int ID_TRANG_THAI { get; set; }
        public int ID_DANH_MUC { get; set; }
        public int ID_TAC_GIA { get; set; }
        public int ID_NXB { get; set; }
        public int ID_The_Loai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Danh_Muc Danh_Muc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gio_Hang> Gio_Hang { get; set; }
        public virtual Nha_Xuat_Ban Nha_Xuat_Ban { get; set; }
        public virtual Tac_Gia Tac_Gia { get; set; }
        public virtual The_Loai The_Loai { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
    }
    public class San_PhamMetadata
    {
        [Required(ErrorMessage = "Tên sản phẩm không được để trống")]
        [StringLength(100, ErrorMessage = "Tên sản phẩm tối đa 100 ký tự")]
        public string TEN_SP { get; set; }

        [Required(ErrorMessage = "Mô tả không được để trống")]
        public string MO_TA { get; set; }

        [Required(ErrorMessage = "Giá gốc không được để trống")]
        [Range(1000, 100000000000, ErrorMessage = "Giá gốc phải từ 1.000 ")]
        public decimal GIA_GOC { get; set; }

        [Range(0, 50, ErrorMessage = "Giảm giá phải từ 0 đến 50%")]
        public Nullable<int> DISCOUNT { get; set; }

        [Required(ErrorMessage = "Tồn kho không được để trống")]
        [Range(0, int.MaxValue, ErrorMessage = "Tồn kho phải lớn hơn hoặc bằng 0")]
        public int TON_KHO { get; set; }

        [Required(ErrorMessage = "Danh mục bắt buộc chọn")]
        public int ID_DANH_MUC { get; set; }

        [Required(ErrorMessage = "Tác giả bắt buộc chọn")]
        public int ID_TAC_GIA { get; set; }

        [Required(ErrorMessage = "NXB bắt buộc chọn")]
        public int ID_NXB { get; set; }

        [Required(ErrorMessage = "Thể loại bắt buộc chọn")]
        public int ID_The_Loai { get; set; }

        [Required(ErrorMessage = "Trạng thái bắt buộc chọn")]
        public int ID_TRANG_THAI { get; set; }
    }
}
