//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int ID_THANHTOAN { get; set; }
        public int ID_DON_HANG { get; set; }
        public int ID_PHUONG_THUC { get; set; }
        public Nullable<decimal> GIA_BAN { get; set; }
        public Nullable<System.DateTime> ThoiGianThanhToan { get; set; }
        public string AnhThanhToan { get; set; }
        public int ID_TRANG_THAI { get; set; }
    
        public virtual Don_Hang Don_Hang { get; set; }
        public virtual Phuong_Thuc_Thanh_Toan Phuong_Thuc_Thanh_Toan { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
    }
}
