//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_Gia
    {
        public int ID_DANH_GIA { get; set; }
        public string MA_KH { get; set; }
        public string MA_SP { get; set; }
        public Nullable<int> DIEM_DANH_GIA { get; set; }
        public string NHAN_XET { get; set; }
        public Nullable<System.DateTime> NGAY_DANH_GIA { get; set; }
    
        public virtual Khach_Hang Khach_Hang { get; set; }
        public virtual San_Pham San_Pham { get; set; }
    }
}
