//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Don_Hang()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
            this.Lich_Su_Don_Hang = new HashSet<Lich_Su_Don_Hang>();
        }
    
        public int ID_DON_HANG { get; set; }
        public string MA_KH { get; set; }
        public Nullable<System.DateTime> TG_DAT_HANG { get; set; }
        public Nullable<int> ID_TRANG_THAI { get; set; }
        public Nullable<decimal> TONG_TIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lich_Su_Don_Hang> Lich_Su_Don_Hang { get; set; }
        public virtual Khach_Hang Khach_Hang { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
    }
}
