//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Project_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> ID_ROLE { get; set; }
        public string MA_KH { get; set; }
    
        public virtual Khach_Hang Khach_Hang { get; set; }
        public virtual Role Role { get; set; }
    }
}
